name: punchking-prod-frontend

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_MODE: production
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}

    image: punch-king-prod-frontend:latest
    container_name: punch-king-prod-frontend
    restart: always

    ports:
      - "3001:80"

    environment:
      NODE_ENV: production

    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

networks:
  default:
    name: punch_king_network
    external: true