name: punchking-prod-frontend     # ← add this

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_MODE=production
    image: punch-king-prod-frontend:latest
    container_name: punch-king-prod-frontend
    restart: always
    env_file:
      - .env
    ports:
      - "3001:80"
    environment:
      VITE_API_BASE_URL: https://api.punchkingboxing.com
      NODE_ENV: production
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
networks:
  default:
    name: punch_king_network
    external: true
